# PersistentVolumeClaim for Redis data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: sparql-agent
  labels:
    app: sparql-agent
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Change to your storage class
  resources:
    requests:
      storage: 5Gi

---
# PersistentVolumeClaim for application data (optional)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparql-agent-data-pvc
  namespace: sparql-agent
  labels:
    app: sparql-agent
spec:
  accessModes:
    - ReadWriteMany  # Use ReadWriteMany for shared storage across pods
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
