"""
Core abstractions and types for the SPARQL-LLM system.

This package provides the foundational abstractions, types, and exceptions
used throughout the SPARQL-Agent system.
"""

# Import abstract base classes
from .base import (
    LLMProvider,
    OntologyProvider,
    QueryGenerator,
    ResultFormatter,
    SchemaDiscoverer,
    SPARQLEndpoint,
)

# Import all exception types
from .exceptions import (
    AmbiguousQueryError,
    CacheError,
    CacheInvalidationError,
    CacheReadError,
    CacheWriteError,
    ConfigurationError,
    ConfigurationLoadError,
    ConstraintViolationError,
    EndpointAuthenticationError,
    EndpointConnectionError,
    EndpointError,
    EndpointNotFoundError,
    EndpointRateLimitError,
    EndpointTimeoutError,
    EndpointUnavailableError,
    FormattingError,
    FormattingNotSupportedError,
    InputValidationError,
    InsufficientContextError,
    InvalidConfigurationError,
    InvalidFormatError,
    LLMAuthenticationError,
    LLMConnectionError,
    LLMContentFilterError,
    LLMError,
    LLMModelNotFoundError,
    LLMQuotaExceededError,
    LLMRateLimitError,
    LLMResponseError,
    LLMTimeoutError,
    MissingConfigurationError,
    NaturalLanguageParseError,
    OntologyClassNotFoundError,
    OntologyError,
    OntologyInconsistentError,
    OntologyLoadError,
    OntologyNotFoundError,
    OntologyParseError,
    OntologyPropertyNotFoundError,
    OntologyValidationError,
    OutputValidationError,
    QueryError,
    QueryExecutionError,
    QueryGenerationError,
    QueryMappingError,
    QueryOptimizationError,
    QueryResultError,
    QuerySyntaxError,
    QueryTimeoutError,
    QueryTooComplexError,
    QueryValidationError,
    ResourceError,
    ResourceExhaustedError,
    ResourceLockedError,
    ResourceNotFoundError,
    SchemaDiscoveryError,
    SchemaError,
    SchemaIncompleteError,
    SchemaNotFoundError,
    SchemaValidationError,
    SerializationError,
    SPARQLAgentError,
    ValidationError,
)

# Import all types
from .types import (
    EndpointInfo,
    FormattedResult,
    GeneratedQuery,
    LLMResponse,
    OntologyInfo,
    OWLClass,
    OWLProperty,
    OWLPropertyType,
    OWLRestrictionType,
    QueryResult,
    QueryStatus,
    SchemaInfo,
)

__all__ = [
    # Abstract base classes
    "SPARQLEndpoint",
    "OntologyProvider",
    "SchemaDiscoverer",
    "QueryGenerator",
    "LLMProvider",
    "ResultFormatter",
    # Core types
    "QueryStatus",
    "OWLPropertyType",
    "OWLRestrictionType",
    "OWLClass",
    "OWLProperty",
    "OntologyInfo",
    "EndpointInfo",
    "SchemaInfo",
    "QueryResult",
    "LLMResponse",
    "GeneratedQuery",
    "FormattedResult",
    # Exceptions - Base
    "SPARQLAgentError",
    # Exceptions - Endpoint
    "EndpointError",
    "EndpointConnectionError",
    "EndpointTimeoutError",
    "EndpointAuthenticationError",
    "EndpointNotFoundError",
    "EndpointRateLimitError",
    "EndpointUnavailableError",
    # Exceptions - Query
    "QueryError",
    "QuerySyntaxError",
    "QueryValidationError",
    "QueryExecutionError",
    "QueryTimeoutError",
    "QueryResultError",
    "QueryTooComplexError",
    # Exceptions - Schema
    "SchemaError",
    "SchemaDiscoveryError",
    "SchemaValidationError",
    "SchemaNotFoundError",
    "SchemaIncompleteError",
    # Exceptions - Ontology
    "OntologyError",
    "OntologyLoadError",
    "OntologyParseError",
    "OntologyValidationError",
    "OntologyNotFoundError",
    "OntologyInconsistentError",
    "OntologyClassNotFoundError",
    "OntologyPropertyNotFoundError",
    # Exceptions - LLM
    "LLMError",
    "LLMConnectionError",
    "LLMAuthenticationError",
    "LLMRateLimitError",
    "LLMTimeoutError",
    "LLMResponseError",
    "LLMModelNotFoundError",
    "LLMQuotaExceededError",
    "LLMContentFilterError",
    # Exceptions - Query Generation
    "QueryGenerationError",
    "NaturalLanguageParseError",
    "QueryMappingError",
    "QueryOptimizationError",
    "InsufficientContextError",
    "AmbiguousQueryError",
    # Exceptions - Formatting
    "FormattingError",
    "InvalidFormatError",
    "FormattingNotSupportedError",
    "SerializationError",
    # Exceptions - Configuration
    "ConfigurationError",
    "InvalidConfigurationError",
    "MissingConfigurationError",
    "ConfigurationLoadError",
    # Exceptions - Validation
    "ValidationError",
    "InputValidationError",
    "OutputValidationError",
    "ConstraintViolationError",
    # Exceptions - Resource
    "ResourceError",
    "ResourceNotFoundError",
    "ResourceExhaustedError",
    "ResourceLockedError",
    # Exceptions - Cache
    "CacheError",
    "CacheReadError",
    "CacheWriteError",
    "CacheInvalidationError",
]
